[project]
name = "nyfitsa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.9.2",
    "requests>=2.32.3",
    "tyro>=0.8.11",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]

